import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function feedOffice() {
  await prisma.office.createMany({
    data: [
      {
        name: 'JYP Entertainment',
      },
      {
        name: 'SM Entertainment',
      },
      {
        name: 'YG Entertainment',
      },
      {
        name: 'HYBE',
      },
      {
        name: 'BIGHIT MUSIC',
      },
      {
        name: 'MYSTIC STORY',
      },
      {
        name: 'n.CH Entertainment',
      },
      {
        name: 'RBW',
      },
      {
        name: 'WAKEONE',
      },
      {
        name: 'CUBE Entertainment',
      },
      {
        name: 'MLD Entertainment',
      },
    ],
  });
}

async function feedArtist() {
  await prisma.artist.createMany({
    data: [
      // JYP
      {
        name: 'TWICE',
        debut: new Date('2015-10-20'),
        photo: '/images/artist/twice.jpeg',
        logo: '/images/logo/twice.png',
        officeId: 1,
      },
      {
        name: 'Stray Kids',
        debut: new Date('2018-03-25'),
        photo: '/images/artist/straykids.jpeg',
        logo: '/images/logo/straykids.png',
        officeId: 1,
      },
      {
        name: 'ITZY',
        debut: new Date('2019-02-12'),
        photo: '/images/artist/itzy.jpeg',
        logo: '/images/logo/itzy.png',
        officeId: 1,
      },
      {
        name: 'NiziU',
        debut: new Date('2020-12-02'),
        photo: '/images/artist/niziu.png',
        logo: '/images/logo/niziu.png',
        officeId: 1,
      },
      {
        name: 'NMIXX',
        debut: new Date('2022-02-22'),
        photo: '/images/artist/nmixx.jpeg',
        logo: '/images/logo/nmixx.png',
        officeId: 1,
      },
      // SM ENTERTAINMENT
      {
        name: "Girls' Generation",
        debut: new Date('2007-08-01'),
        photo: "/images/artist/girlsgeneration.jpeg",
        logo: "/images/logo/girlsgeneration.jpeg",
        officeId: 2,
      },
      {
        name: 'Red Velvet',
        debut: new Date('2014-08-01'),
        photo: '/images/artist/redvelvet.webp',
        logo: '/images/logo/redvelvet.png',
        officeId: 2,
      },
      {
        name: 'aespa',
        debut: new Date('2020-11-17'),
        photo: '/images/artist/aespa.jpeg',
        logo: '/images/logo/aespa.png',
        officeId: 2,
      },
      // YG ENTERTAINMENT
      {
        name: 'BIGBANG',
        debut: new Date('2006-08-19'),
        photo: '/images/artist/bigbang.webp',
        logo: '/images/logo/bigbang.png',
        officeId: 3,
      },
      {
        name: 'BLACKPINK',
        debut: new Date('2006-08-08'),
        photo: '/images/artist/blackpink.jpeg',
        logo: '/images/logo/blackpink.png',
        officeId: 3,
      },
      // BIGHIT
      {
        name: 'BTS',
        debut: new Date('2013-06-13'),
        photo: '/images/artist/bts.jpeg',
        logo: '/images/logo/bts.png',
        officeId: 5,
      },
      // HYBE
      {
        name: 'fromis_9',
        debut: new Date('2018-01-24'),
        photo: '/images/artist/fromis_9.jpeg',
        logo: '/images/logo/fromis_9.png',
        officeId: 4,
      },
      {
        name: 'LE SSERAFIM',
        debut: new Date('2022-05-02'),
        photo: '/images/artist/le-sserafim.jpeg',
        logo: '/images/logo/le-sserafim.svg',
        officeId: 4,
      },
      {
        name: 'NEWJEANS',
        debut: new Date('2022-07-22'),
        photo: '/images/artist/newjeans.jpeg',
        logo: '/images/logo/newjeans.svg',
        officeId: 4,
      },
      // MYSTIC STORY
      {
        name: 'Billlie',
        debut: new Date('2021-11-10'),
        photo: '/images/artist/billlie.jpeg',
        logo: '/images/logo/billie.jpeg',
        officeId: 6,
      },
      // n.CH Entertainment
      {
        name: 'NATURE',
        debut: new Date('2018-08-03'),
        photo: '/images/artist/nature.jpeg',
        logo: '/images/logo/nature.png',
        officeId: 7,
      },
      // RBW
      {
        name: 'MAMAMOO',
        debut: new Date('2014-06-19'),
        photo: '/images/artist/mamamoo.jpeg',
        logo: '/images/logo/mamamoo.png',
        officeId: 8,
      },
      // WAKEONE
      {
        name: 'Kep1er',
        debut: new Date('2022-01-03'),
        photo: '/images/artist/kep1er.jpeg',
        logo: '/images/logo/kep1er.png',
        officeId: 9,
      },
      // CUBE Entertainment
      {
        name: '(G)I-DLE',
        debut: new Date('2018-05-02'),
        photo: '/images/artist/gi-dle.jpeg',
        logo: '/images/logo/gi-dle.webp',
        officeId: 10,
      },
      // MLD Entertainment
      {
        name: 'MOMOLAND',
        debut: new Date('2016-11-10'),
        photo: '/images/artist/momoland.jpeg',
        logo: '/images/logo/momoland.png',
        officeId: 11,
      },
    ],
  });
}

async function feedMusic() {
  await prisma.music.createMany({
    data: [
      // TWICE
      {
        id: 'k6jqx9kZgPM',
        name: 'Talk that Talk',
        url: 'https://youtu.be/k6jqx9kZgPM',
        date: new Date('2022-08-26'),
        artistId: 1,
      },
      {
        id: 'fMIn43MiwG8',
        name: 'Celebrate',
        url: 'https://youtu.be/fMIn43MiwG8',
        date: new Date('2022-07-15'),
        artistId: 1,
      },
      {
        id: 'f5_wn8mexmM',
        name: 'The Feels',
        url: 'https://youtu.be/f5_wn8mexmM',
        date: new Date('2021-10-01'),
        artistId: 1,
      },
      {
        id: '3ymwOvzhwHs',
        name: 'Feel Special',
        url: 'https://youtu.be/3ymwOvzhwHs',
        date: new Date('2019-09-23'),
        artistId: 1,
      },
      {
        id: 'CM4CkVFmTds',
        name: "I CAN'T STOP ME",
        url: 'https://youtu.be/CM4CkVFmTds',
        date: new Date('2020-10-26'),
        artistId: 1,
      },
      {
        id: 'rRzxEiBLQCA',
        name: 'Heart Shaker',
        url: 'https://youtu.be/rRzxEiBLQCA',
        date: new Date('2017-12-11'),
        artistId: 1,
      },
      {
        id: 'V2hlQkVJZhE',
        name: 'LIKEY',
        url: 'https://youtu.be/V2hlQkVJZhE',
        date: new Date('2017-10-30'),
        artistId: 1,
      },
      {
        id: 'VQtonf1fv_s',
        name: 'SIGNAL',
        url: 'https://youtu.be/VQtonf1fv_s',
        date: new Date('2017-05-15'),
        artistId: 1,
      },
      {
        id: 'fmOEKOjyDxU',
        name: 'Perfect World',
        url: 'https://youtu.be/fmOEKOjyDxU',
        date: new Date('2021-06-30'),
        artistId: 1,
      },
      {
        id: '8A2t_tAjMz8',
        name: 'KNOCK KNOCK',
        url: 'https://youtu.be/8A2t_tAjMz8',
        date: new Date('2017-02-20'),
        artistId: 1,
      },
      {
        id: 'kOHB85vDuow',
        name: 'FANCY',
        url: 'https://youtu.be/kOHB85vDuow',
        date: new Date('2019-04-22'),
        artistId: 1,
      },
      {
        id: 'i0p1bmr0EmE',
        name: 'What is Love?',
        url: 'https://youtu.be/i0p1bmr0EmE',
        date: new Date('2018-04-09'),
        artistId: 1,
      },
      {
        id: 'ZdKYi5ekshM',
        name: 'Breakthrough',
        url: 'https://youtu.be/ZdKYi5ekshM',
        date: new Date('2019-06-12'),
        artistId: 1,
      },
      {
        id: 'HuoOEry-Yc4',
        name: 'One More Time',
        url: 'https://youtu.be/HuoOEry-Yc4',
        date: new Date('2017-10-06'),
        artistId: 1,
      },
      {
        id: 'DdLYSziSXII',
        name: 'Wake Me Up',
        url: 'https://youtu.be/DdLYSziSXII',
        date: new Date('2018-04-25'),
        artistId: 1,
      },
      {
        id: 'X3H-4crGD6k',
        name: 'I WANT YOU BACK',
        url: 'https://youtu.be/X3H-4crGD6k',
        date: new Date('2018-06-15'),
        artistId: 1,
      },
      {
        id: 'vPwaXytZcgI',
        name: 'SCIENTIST',
        url: 'https://youtu.be/vPwaXytZcgI',
        date: new Date('2021-11-12'),
        artistId: 1,
      },
      {
        id: 'XA2YEHn-A8Q',
        name: 'Alcohol-Free',
        url: 'https://youtu.be/XA2YEHn-A8Q',
        date: new Date('2021-06-09'),
        artistId: 1,
      },
      {
        id: 'mAKsZ26SabQ',
        name: 'YES or YES',
        url: 'https://youtu.be/mAKsZ26SabQ',
        date: new Date('2018-11-05'),
        artistId: 1,
      },
      {
        id: 'BSS8Y-0hOlY',
        name: 'Kura Kura',
        url: 'https://youtu.be/BSS8Y-0hOlY',
        date: new Date('2021-04-21'),
        artistId: 1,
      },
      {
        id: '0rtV5esQT6I',
        name: 'Like OOH-AHH(OOH-AHH하게)',
        url: 'https://youtu.be/0rtV5esQT6I',
        date: new Date('2015-10-20'),
        artistId: 1,
      },
      {
        id: 'ePpPVE-GGJw',
        name: 'TT',
        url: 'https://youtu.be/ePpPVE-GGJw',
        date: new Date('2016-10-24'),
        artistId: 1,
      },
      {
        id: 'wQ_POfToaVY',
        name: 'Candy Pop',
        url: 'https://youtu.be/wQ_POfToaVY',
        date: new Date('2018-01-12'),
        artistId: 1,
      },
      {
        id: 'mH0_XpSHkZo',
        name: 'MORE & MORE',
        url: 'https://youtu.be/mH0_XpSHkZo',
        date: new Date('2020-06-01'),
        artistId: 1,
      },
      {
        id: 'CMNahhgR_ss',
        name: 'BDZ',
        url: 'https://youtu.be/CMNahhgR_ss',
        date: new Date('2018-08-17'),
        artistId: 1,
      },
      {
        id: 'zQELp93xxfo',
        name: 'Fake & True',
        url: 'https://youtu.be/zQELp93xxfo',
        date: new Date('2019-10-18'),
        artistId: 1,
      },
      // StrayKids
      {
        id: 'jYSlpC6Ud2A',
        name: 'CASE 143',
        url: 'https://youtu.be/jYSlpC6Ud2A',
        date: new Date('2022-10-07'),
        artistId: 2,
      },
      {
        id: 'EaswWiwMVs8',
        name: '소리꾼(Thunderous)',
        url: 'https://youtu.be/EaswWiwMVs8',
        date: new Date('2021-08-23'),
        artistId: 2,
      },
      {
        id: 'OvioeS1ZZ7o',
        name: 'MANIAC',
        url: 'https://youtu.be/OvioeS1ZZ7o',
        date: new Date('2022-03-18'),
        artistId: 2,
      },
      {
        id: 'X-uJtV8ScYk',
        name: 'Back Door',
        url: 'https://youtu.be/X-uJtV8ScYk',
        date: new Date('2020-09-14'),
        artistId: 2,
      },
      {
        id: 'TQTlCHxyuu8',
        name: "神메뉴(God's Menu)",
        url: 'https://youtu.be/TQTlCHxyuu8',
        date: new Date('2020/06/17'),
        artistId: 2,
      },
      // ITZY
      {
        id: 'zugAhfd2r0g',
        name: 'Cheshire',
        url: 'https://youtu.be/zugAhfd2r0g',
        date: new Date('2022-11-30'),
        artistId: 3,
      },
      {
        id: 'pNfTK39k55U',
        name: '달라달라(DALLA DALLA)',
        url: 'https://youtu.be/pNfTK39k55U',
        date: new Date('2019-02-11'),
        artistId: 3,
      },
      {
        id: 'zndvqTc4P9I',
        name: 'ICY',
        url: 'https://youtu.be/zndvqTc4P9I',
        date: new Date('2019-07-29'),
        artistId: 3,
      },
      {
        id: 'wTowEKjDGkU',
        name: 'Not Shy',
        url: 'https://youtu.be/wTowEKjDGkU',
        date: new Date('2020-08-17'),
        artistId: 3,
      },
      {
        id: '_ysomCGaZLw',
        name: '마.피.아. In the morning',
        url: 'https://youtu.be/_ysomCGaZLw',
        date: new Date('2021-04-30'),
        artistId: 3,
      },
      {
        id: '9oyodEkzn94',
        name: 'SWIPE',
        url: 'https://youtu.be/9oyodEkzn94',
        date: new Date('2021-09-26'),
        artistId: 3,
      },
      {
        id: 'MjCZfZfucEc',
        name: 'LOCO',
        url: 'https://youtu.be/MjCZfZfucEc',
        date: new Date('2021-09-24'),
        artistId: 3,
      },
      {
        id: 'fE2h3lGlOsk',
        name: 'WANNABE',
        url: 'https://youtu.be/fE2h3lGlOsk',
        date: new Date('2020-03-09'),
        artistId: 3,
      },
      {
        id: 'Hbb5GPxXF1w',
        name: 'SNEAKERS',
        url: 'https://youtu.be/Hbb5GPxXF1w',
        date: new Date('2022-07-15'),
        artistId: 3,
      },
      {
        id: 'F-QTb-0wRGk',
        name: 'Blah Blah Blah',
        url: 'https://youtu.be/F-QTb-0wRGk',
        date: new Date('2022-09-21'),
        artistId: 3,
      },
      {
        id: '6uZy86ePgO0',
        name: 'Boys Like You',
        url: 'https://youtu.be/6uZy86ePgO0',
        date: new Date('2022-10-21'),
        artistId: 3,
      },
      // NiziU
      {
        id: 'QW28YKqdxe0',
        name: 'Make you Happy',
        url: 'https://youtu.be/QW28YKqdxe0',
        date: new Date('2020-06-30'),
        artistId: 4,
      },
      {
        id: 'mgYnKfgx6tI',
        name: 'Poppin’ Shakin’',
        url: 'https://youtu.be/mgYnKfgx6tI',
        date: new Date('2021-04-07'),
        artistId: 4,
      },
      {
        id: 'OlHb1qH-zS4',
        name: 'Take a picture',
        url: 'https://youtu.be/OlHb1qH-zS4',
        date: new Date('2021-03-29'),
        artistId: 4,
      },
      {
        id: 'nCjmXHsRJNY',
        name: 'Chopstick',
        url: 'https://youtu.be/nCjmXHsRJNY',
        date: new Date('2021-11-11'),
        artistId: 4,
      },
      {
        id: 'a6QT0acJFQE',
        name: 'Step and a step',
        url: 'https://youtu.be/a6QT0acJFQE',
        date: new Date('2020-11-24'),
        artistId: 4,
      },
      {
        id: 'SpPY1T8UU7Y',
        name: 'ASOBO',
        url: 'https://youtu.be/SpPY1T8UU7Y',
        date: new Date('2022-04-12'),
        artistId: 4,
      },
      {
        id: 'IN7WgihC8Fs',
        name: 'CLAP CLAP',
        url: 'https://youtu.be/IN7WgihC8Fs',
        date: new Date('2022-07-13'),
        artistId: 4,
      },
      {
        id: 'exOeLmxIcCo',
        name: 'Blue Moon',
        url: 'https://youtu.be/exOeLmxIcCo',
        date: new Date('2022-12-02'),
        artistId: 4,
      },
      // NMIXX
      {
        id: 'p1bjnyDqI9k',
        name: 'Dice',
        url: 'https://youtu.be/p1bjnyDqI9k',
        date: new Date('2022-09-19'),
        artistId: 5,
      },
      {
        id: 'kBwikDvbRbI',
        name: 'Funky Glitter Christmas',
        url: 'https://youtu.be/kBwikDvbRbI',
        date: new Date('2022-11-23'),
        artistId: 5,
      },
      {
        id: '3GWscde8rM8',
        name: 'O.O',
        url: 'https://youtu.be/3GWscde8rM8',
        date: new Date('2022-02-22'),
        artistId: 5,
      },
      // Girls' Generation
      {
        id: '0k2Zzkw_-0I',
        name: '다시 만난 세계 (Into The New World)',
        url: 'https://youtu.be/0k2Zzkw_-0I',
        date: new Date('2011-06-03'),
        artistId: 6,
      },
      {
        id: 'U7mPqycQ0tQ',
        name: 'Gee',
        url: 'https://youtu.be/U7mPqycQ0tQ',
        date: new Date('2009-06-08'),
        artistId: 6,
      },
      {
        id: 'Fzr2Nv8NTEE',
        name: 'MR. TAXI',
        url: 'https://youtu.be/Fzr2Nv8NTEE',
        date: new Date('2012-04-03'),
        artistId: 6,
      },
      {
        id: 'Qpf26PtBXgo',
        name: 'FOREVER 1',
        url: 'https://youtu.be/Qpf26PtBXgo',
        date: new Date('2022-08-05'),
        artistId: 6,
      },
      // Red Velvet
      {
        id: 'aiHSVQy9xN8',
        name: 'Power Up',
        url: 'https://youtu.be/aiHSVQy9xN8',
        date: new Date('2018-08-06'),
        artistId: 7,
      },
      {
        id: '6uJf2IT2Zh8',
        name: '피카부 (Peek-A-Boo)',
        url: 'https://youtu.be/6uJf2IT2Zh8',
        date: new Date('2017-11-17'),
        artistId: 7,
      },
      {
        id: 'QslJYDX3o8s',
        name: '러시안 룰렛 (Russian Roulette)',
        url: 'https://youtu.be/QslJYDX3o8s',
        date: new Date('2016-09-07'),
        artistId: 7,
      },
      {
        id: 'WyiIGEHQP8o',
        name: '빨간 맛 (Red Flavor)',
        url: 'https://youtu.be/WyiIGEHQP8o',
        date: new Date('2017-07-09'),
        artistId: 7,
      },
      {
        id: 'IWJUPY-2EIM',
        name: 'RBB (Really Bad Boy)',
        url: 'https://youtu.be/IWJUPY-2EIM',
        date: new Date('2018-11-30'),
        artistId: 7,
      },
      {
        id: 'uR8Mrt1IpXg',
        name: 'Psycho',
        url: 'https://youtu.be/uR8Mrt1IpXg',
        date: new Date('2019-12-23'),
        artistId: 7,
      },
      {
        id: 'rRgTMs_bGuI',
        name: '#Cookie Jar',
        url: 'https://youtu.be/rRgTMs_bGuI',
        date: new Date('2018-06-21'),
        artistId: 7,
      },
      // aespa
      {
        id: '4TWR90KJl84',
        name: 'Next Level',
        url: 'https://youtu.be/4TWR90KJl84',
        date: new Date('2021-05-17'),
        artistId: 8,
      },
      {
        id: 'ZeerrnuLi5E',
        name: 'Black Mamba',
        url: 'https://youtu.be/ZeerrnuLi5E',
        date: new Date('2020-11-17'),
        artistId: 8,
      },
      {
        id: 'wog1R1d4zls',
        name: 'Forever (약속)',
        url: 'https://youtu.be/wog1R1d4zls',
        date: new Date('2021-02-05'),
        artistId: 8,
      },
      {
        id: 'WPdWvnAAurg',
        name: 'Savage',
        url: 'https://youtu.be/WPdWvnAAurg',
        date: new Date('2021-10-05'),
        artistId: 8,
      },
      {
        id: 'dYRITmpFbJ4',
        name: 'Girls',
        url: 'https://youtu.be/dYRITmpFbJ4',
        date: new Date('2022-07-08'),
        artistId: 8,
      },
      {
        id: 'z2ZjutyxmjA',
        name: "Life's Too Short (English Ver.)",
        url: 'https://youtu.be/z2ZjutyxmjA',
        date: new Date('2022-06-24'),
        artistId: 8,
      },
      {
        id: 'H69tJmsgd9I',
        name: 'Dreams Come True',
        url: 'https://youtu.be/H69tJmsgd9I',
        date: new Date('2021-12-20'),
        artistId: 8,
      },
      {
        id: 'BpCvYeK5hcE',
        name: '도깨비불 (Illusion)',
        url: 'https://youtu.be/BpCvYeK5hcE',
        date: new Date('2022-06-01'),
        artistId: 8,
      },
      {
        id: 'iTgcp1oDk2M',
        name: 'Beautiful Christmas',
        url: 'https://youtu.be/iTgcp1oDk2M',
        date: new Date('2022-12-14'),
        artistId: 8,
      },
      // BigBang
      {
        id: 'fkwPTz67sgI',
        name: 'GARAGARA GO!!(ガラガラ GO!!)',
        url: 'https://youtu.be/fkwPTz67sgI',
        date: new Date('2009-06-30'),
        artistId: 9,
      },
      {
        id: 'AAbokV76tkU',
        name: 'FANTASTIC BABY',
        url: 'https://youtu.be/AAbokV76tkU',
        date: new Date('2012-03-07'),
        artistId: 9,
      },
      {
        id: '2ips2mM7Zqw',
        name: '뱅뱅뱅 (BANG BANG BANG)',
        url: 'https://youtu.be/2ips2mM7Zqw',
        date: new Date('2015-06-02'),
        artistId: 9,
      },
      // Black Pink
      {
        id: 'bwmSjveL3Lc',
        name: '붐바야 (BOOMBAYAH)',
        url: 'https://youtu.be/bwmSjveL3Lc',
        date: new Date('2016-08-08'),
        artistId: 10,
      },
      {
        id: 'dISNgvVpWlo',
        name: '휘파람 (WHISTLE)',
        url: 'https://youtu.be/dISNgvVpWlo',
        date: new Date('2016-08-08'),
        artistId: 10,
      },
      {
        id: 'FzVR_fymZw4',
        name: 'STAY',
        url: 'https://youtu.be/FzVR_fymZw4',
        date: new Date('2016-11-01'),
        artistId: 10,
      },
      {
        id: 'dyRsYk0LyA8',
        name: 'Lovesick Girls',
        url: 'https://youtu.be/dyRsYk0LyA8',
        date: new Date('2020-10-02'),
        artistId: 10,
      },
      {
        id: 'vRXZj0DzXIA',
        name: 'Ice Cream (with Selena Gomez)',
        url: 'https://youtu.be/vRXZj0DzXIA',
        date: new Date('2020-08-28'),
        artistId: 10,
      },
      {
        id: 'ioNng23DkIM',
        name: 'How You Like That',
        url: 'https://youtu.be/ioNng23DkIM',
        date: new Date('2020-06-26'),
        artistId: 10,
      },
      {
        id: '2S24-y0Ij3Y',
        name: 'Kill This Love',
        url: 'https://youtu.be/2S24-y0Ij3Y',
        date: new Date('2019-04-05'),
        artistId: 10,
      },
      {
        id: '9pdj4iJD08s',
        name: '불장난 (PLAYING WITH FIRE)',
        url: 'https://youtu.be/9pdj4iJD08s',
        date: new Date('2016-11-01'),
        artistId: 10,
      },
      {
        id: 'Amq-qlqbjYA',
        name: "마지막처럼 (AS IF IT'S YOUR LAST)",
        url: 'https://youtu.be/Amq-qlqbjYA',
        date: new Date('2017-06-22'),
        artistId: 10,
      },
      {
        id: 'gQlMMD8auMs',
        name: 'Pink Venom',
        url: 'https://youtu.be/gQlMMD8auMs',
        date: new Date('2022-08-19'),
        artistId: 10,
      },
      {
        id: 'POe9SOEKotk',
        name: 'Shut Down',
        url: 'https://youtu.be/POe9SOEKotk',
        date: new Date('2022-09-16'),
        artistId: 10,
      },
      {
        id: '7WyHtSlvHD4',
        name: 'Ready For Love',
        url: 'https://youtu.be/7WyHtSlvHD4',
        date: new Date('2022-07-29'),
        artistId: 10,
      },
      // BTS
      {
        id: 'gdZLi9oWNZg',
        name: 'Dynamite',
        url: 'https://youtu.be/gdZLi9oWNZg',
        date: new Date('2020-08-21'),
        artistId: 11,
      },
      {
        id: 'WMweEpGlu_U',
        name: 'Butter',
        url: 'https://youtu.be/WMweEpGlu_U',
        date: new Date('2021-05-21'),
        artistId: 11,
      },
      {
        id: 'MBdVXkSdhwU',
        name: 'DNA',
        url: 'https://youtu.be/MBdVXkSdhwU',
        date: new Date('2017-09-18'),
        artistId: 11,
      },
      {
        id: 'CuklIb9d3fI',
        name: 'Permission to Dance',
        url: 'https://youtu.be/CuklIb9d3fI',
        date: new Date('2021-07-09'),
        artistId: 11,
      },
      {
        id: 'pBuZEGYXA6E',
        name: 'IDOL',
        url: 'https://youtu.be/pBuZEGYXA6E',
        date: new Date('2018-08-24'),
        artistId: 11,
      },
      // fromis_9
      {
        id: 'JC6budcACNE',
        name: 'Stay This Way',
        url: 'https://youtu.be/JC6budcACNE',
        date: new Date('2022-06-27'),
        artistId: 12,
      },
      {
        id: '4gXmClk8rKI',
        name: 'DM',
        url: 'https://youtu.be/4gXmClk8rKI',
        date: new Date('2022-01-17'),
        artistId: 12,
      },
      {
        id: 'BjmmvBMXbSU',
        name: 'Talk & Talk',
        url: 'https://youtu.be/BjmmvBMXbSU',
        date: new Date('2021-09-01'),
        artistId: 12,
      },
      {
        id: 'zsRyyLtcXho',
        name: 'FUN!',
        url: 'https://youtu.be/zsRyyLtcXho',
        date: new Date('2019-06-04'),
        artistId: 12,
      },
      {
        id: '-SK6cvkK4c0',
        name: 'LOVE BOMB',
        url: 'https://youtu.be/-SK6cvkK4c0',
        date: new Date('2018-10-10'),
        artistId: 12,
      },
      {
        id: 'jLmJhjCzOTw',
        name: 'Feel Good (SECRET CODE)',
        url: 'https://youtu.be/jLmJhjCzOTw',
        date: new Date('2020-09-16'),
        artistId: 12,
      },
      // LE SSERAFIM
      {
        id: '4vbDFu0PUew',
        name: 'FEARLESS',
        url: 'https://youtu.be/4vbDFu0PUew',
        date: new Date('2022-05-02'),
        artistId: 13,
      },
      {
        id: 'pyf8cbqyfPs',
        name: 'ANTIFRAGILE',
        url: 'https://youtu.be/pyf8cbqyfPs',
        date: new Date('2022-10-16'),
        artistId: 13,
      },
      {
        id: 'Ccz123Jlflc',
        name: 'Impurities',
        url: 'https://youtu.be/Ccz123Jlflc',
        date: new Date('2022-11-13'),
        artistId: 13,
      },
      // NEWJEANS
      {
        id: 'pSUydWEqKwE',
        name: 'Ditto',
        url: 'https://youtu.be/pSUydWEqKwE',
        date: new Date('2022/12/19'),
        artistId: 14,
      },
      {
        id: 'js1CtxSY38I',
        name: 'Attention',
        url: 'https://youtu.be/js1CtxSY38I',
        date: new Date('2022-07-22'),
        artistId: 14,
      },
      {
        id: 'VOmIplFAGeg',
        name: 'Cookie',
        url: 'https://youtu.be/VOmIplFAGeg',
        date: new Date('2022/08/01'),
        artistId: 14,
      },
      {
        id: '_ZAgIHmHLdc',
        name: 'OMG',
        url: 'https://youtu.be/_ZAgIHmHLdc',
        date: new Date('2023-01-02'),
        artistId: 14,
      },
      {
        id: 'tVIXY14aJms',
        name: 'Hurt',
        url: 'https://youtu.be/tVIXY14aJms',
        date: new Date('2022/07/25'),
        artistId: 14,
      },
      // Billlie
      {
        id: 'YKKh8d4wZbU',
        name: 'GingaMingaYo (the strange world)',
        url: 'https://youtu.be/YKKh8d4wZbU',
        date: new Date('2022-02-23'),
        artistId: 15,
      },
      {
        id: 'z8Eu-HU0sWQ',
        name: 'RING ma Bell (what a wonderful world)',
        url: 'https://youtu.be/z8Eu-HU0sWQ',
        date: new Date('2022-08-31'),
        artistId: 15,
      },
      {
        id: 'i9jhxOwcaw0',
        name: 'RING X RING',
        url: 'https://youtu.be/i9jhxOwcaw0',
        date: new Date('2021-11-10'),
        artistId: 15,
      },
      {
        id: 'E9pAsuLD1uU',
        name: 'snowy night',
        url: 'https://youtu.be/E9pAsuLD1uU',
        date: new Date('2021-12-14'),
        artistId: 15,
      },
      // NATURE
      {
        id: 'bEwIlxtw9w4',
        name: 'LIMBO! (넘어와)',
        url: 'https://youtu.be/bEwIlxtw9w4',
        date: new Date('2022-11-06'),
        artistId: 16,
      },
      {
        id: 'It4HuJD49d4',
        name: 'RICA RICA',
        url: 'https://youtu.be/It4HuJD49d4',
        date: new Date('2022-01-24'),
        artistId: 16,
      },
      // MAMAMOO
      {
        id: 'KhTeiaCezwM',
        name: 'HIP',
        url: 'https://youtu.be/KhTeiaCezwM',
        date: new Date('2019-11-14'),
        artistId: 17,
      },
      {
        id: 'Vz508O9NNTg',
        name: 'ILLELLA (일낼라)',
        url: 'https://youtu.be/Vz508O9NNTg',
        date: new Date('2022-10-11'),
        artistId: 17,
      },
      {
        id: 'Oao3j2hUVvE',
        name: '고고베베(gogobebe)',
        url: 'https://youtu.be/Oao3j2hUVvE',
        date: new Date('2019-03-14'),
        artistId: 17,
      },
      {
        id: 'BLg_uXvSj-8',
        name: 'Dingga -Japanese ver.-',
        url: 'https://youtu.be/BLg_uXvSj-8',
        date: new Date('2021-01-20'),
        artistId: 17,
      },
      {
        id: 'UoI9riNffEU',
        name: 'AYA',
        url: 'https://youtu.be/UoI9riNffEU',
        date: new Date('2020-11-03'),
        artistId: 17,
      },
      {
        id: 'G5UM2rOyqr4',
        name: '너나 해(Egotistic)',
        url: 'https://youtu.be/G5UM2rOyqr4',
        date: new Date('2018-07-16'),
        artistId: 17,
      },
      {
        id: '3IIBVnn4eTM',
        name: 'Piano Man',
        url: 'https://youtu.be/3IIBVnn4eTM',
        date: new Date('2014-11-21'),
        artistId: 17,
      },
      {
        id: 'LjUXm0Zy_dk',
        name: '별이 빛나는 밤(Starry night)',
        url: 'https://youtu.be/LjUXm0Zy_dk',
        date: new Date('2018-03-07'),
        artistId: 17,
      },
      // Kep1er
      {
        id: 'n0j5NPptyM0',
        name: 'WA DA DA',
        url: 'https://youtu.be/n0j5NPptyM0',
        date: new Date('2022-01-03'),
        artistId: 18,
      },
      {
        id: 'hr-325mclek',
        name: 'Up!',
        url: 'https://youtu.be/hr-325mclek',
        date: new Date('2022-06-20'),
        artistId: 18,
      },
      {
        id: 'zkvIzKwzYNc',
        name: 'We Fresh',
        url: 'https://youtu.be/zkvIzKwzYNc',
        date: new Date('2022-10-13'),
        artistId: 18,
      },
      {
        id: 'w8N3nZ7reZk',
        name: 'Sugar Rush',
        url: 'https://youtu.be/w8N3nZ7reZk',
        date: new Date('2022-09-28'),
        artistId: 18,
      },
      {
        id: 'eK4i2oN8jCk',
        name: 'Wing Wing',
        url: 'https://youtu.be/eK4i2oN8jCk',
        date: new Date('2022-08-03'),
        artistId: 18,
      },
      // (G)I-DLE
      {
        id: 'Jh4QFaPmdss',
        name: 'TOMBOY',
        url: 'https://youtu.be/Jh4QFaPmdss',
        date: new Date('2022-03-14'),
        artistId: 19,
      },
      {
        id: 'fCO7f0SmrDc',
        name: 'Nxde',
        url: 'https://youtu.be/fCO7f0SmrDc',
        date: new Date('2022-10-17'),
        artistId: 19,
      },
      {
        id: '9mQk7Evt6Vs',
        name: 'LATATA',
        url: 'https://youtu.be/9mQk7Evt6Vs',
        date: new Date('2018-05-02'),
        artistId: 19,
      },
      // MOMOLAND
      {
        id: 'JQGRg8XBnB4',
        name: 'BBoom BBoom (뿜뿜)',
        url: 'https://youtu.be/JQGRg8XBnB4',
        date: new Date('2018-01-03'),
        artistId: 20,
      },
      {
        id: 'txWmd7QKFe8',
        name: 'BAAM',
        url: 'https://youtu.be/txWmd7QKFe8',
        date: new Date('2018-06-26'),
        artistId: 20,
      },
      {
        id: 'tsN-MkpiZB0',
        name: "I'm So Hot",
        url: 'https://youtu.be/tsN-MkpiZB0',
        date: new Date('2019-03-20'),
        artistId: 20,
      },
      {
        id: 'TkSv0TkvTRs',
        name: 'Wonderful love(어마어마해)',
        url: 'https://youtu.be/TkSv0TkvTRs',
        date: new Date('2017-04-26'),
        artistId: 20,
      },
    ],
  });
}

async function feedMember() {
  await prisma.member.createMany({
    data: [
      // TWICE
      {
        eName: 'Nayeon',
        jName: 'ナヨン',
        photo: '/images/member/nayeon.jpeg',
        birth: new Date('1995-09-22'),
        type: 'A',
        artistId: 1,
      },
      {
        eName: 'Jeongyeon',
        jName: 'ジョンヨン',
        photo: '/images/member/jeongyeon.jpeg',
        birth: new Date('1996-11-01'),
        type: 'O',
        artistId: 1,
      },
      {
        eName: 'Momo',
        jName: 'モモ',
        birth: new Date('1996-11-09'),
        type: 'A',
        photo: '/images/member/momo.jpeg',
        artistId: 1,
      },
      {
        eName: 'Sana',
        jName: 'サナ',
        birth: new Date('1996-12-29'),
        type: 'B',
        photo: '/images/member/sana.jpeg',
        artistId: 1,
      },
      {
        eName: 'Jihyo',
        jName: 'ジヒョ',
        photo: '/images/member/jihyo.jpeg',
        birth: new Date('1997-02-01'),
        type: 'O',
        artistId: 1,
      },
      {
        eName: 'Mina',
        jName: 'ミナ',
        photo: '/images/member/mina.jpeg',
        birth: new Date('1997-03-24'),
        type: 'A',
        artistId: 1,
      },
      {
        eName: 'Dahyun',
        jName: 'ダヒョン',
        photo: '/images/member/dahyun.jpeg',
        birth: new Date('1998-05-28'),
        type: 'O',
        artistId: 1,
      },
      {
        eName: 'Chaeyoung',
        jName: 'チェヨン',
        photo: '/images/member/chaeyoung.jpeg',
        birth: new Date('1999-04-23'),
        type: 'B',
        artistId: 1,
      },
      {
        eName: 'Tzuyu',
        jName: 'ツゥイ',
        photo: '/images/member/tzuyu.jpeg',
        birth: new Date('1999-06-14'),
        type: 'A',
        artistId: 1,
      },
      // Stray Kids
      {
        eName: 'BangChan',
        jName: 'バンチャン',
        photo: '/images/member/bangchan.jpeg',
        birth: new Date('1997-10-03'),
        type: 'O',
        artistId: 2,
      },
      {
        eName: 'LeeKnow',
        jName: 'リノ',
        photo: '/images/member/leeknow.jpeg',
        birth: new Date('1998-10-25'),
        type: 'O',
        artistId: 2,
      },
      {
        eName: 'Changbin',
        jName: 'チャンビン',
        photo: '/images/member/changbin.jpeg',
        birth: new Date('1999-08-11'),
        type: 'O',
        artistId: 2,
      },
      {
        eName: 'Hyunjin',
        jName: 'ヒュンジン',
        photo: '/images/member/hyunjin.jpeg',
        birth: new Date('2000-03-20'),
        type: 'B',
        artistId: 2,
      },
      {
        eName: 'Han',
        jName: 'ハン',
        photo: '/images/member/han.jpeg',
        birth: new Date('2000-09-14'),
        type: 'B',
        artistId: 2,
      },
      {
        eName: 'Felix',
        jName: 'フィリックス',
        photo: '/images/member/felix.jpeg',
        birth: new Date('2000-09-15'),
        type: 'AB',
        artistId: 2,
      },
      {
        eName: 'Seungmin',
        jName: 'スンミン',
        photo: '/images/member/seungmin.jpeg',
        birth: new Date('2000-09-22'),
        type: 'A',
        artistId: 2,
      },
      {
        eName: 'I.N',
        jName: 'アイエン',
        photo: '/images/member/i.n.jpeg',
        birth: new Date('2001-02-08'),
        type: 'A',
        artistId: 2,
      },
      // ITZY
      {
        eName: 'Yeji',
        jName: 'イェジ',
        photo: '/images/member/yeji.jpeg',
        birth: new Date('2000-05-26'),
        type: 'A',
        artistId: 3,
      },
      {
        eName: 'Lia',
        jName: 'リア',
        photo: '/images/member/lia.jpeg',
        birth: new Date('2000-07-21'),
        type: 'AB',
        artistId: 3,
      },
      {
        eName: 'Ryujin',
        jName: 'リュジン',
        photo: '/images/member/ryujin.jpeg',
        birth: new Date('2001-04-17'),
        type: 'B',
        artistId: 3,
      },
      {
        eName: 'Chaeryeong',
        jName: 'チェリョン',
        photo: '/images/member/chaeryeong.jpeg',
        birth: new Date('2001-06-05'),
        type: 'B',
        artistId: 3,
      },
      {
        eName: 'Yuna',
        jName: 'ユナ',
        photo: '/images/member/yeji.jpeg',
        birth: new Date('2003-12-09'),
        type: 'A',
        artistId: 3,
      },
      // NiziU
      {
        eName: 'Mako',
        jName: 'マコ',
        photo: '/images/member/mako.jpeg',
        birth: new Date('2001-04-04'),
        type: 'A',
        artistId: 4,
      },
      {
        eName: 'Rio',
        jName: 'リオ',
        photo: '/images/member/rio.jpeg',
        birth: new Date('2002-02-04'),
        type: 'B',
        artistId: 4,
      },
      {
        eName: 'Maya',
        jName: 'マヤ',
        photo: '/images/member/maya.jpeg',
        birth: new Date('2002-04-08'),
        type: 'O',
        artistId: 4,
      },
      {
        eName: 'Riku',
        jName: 'リク',
        photo: '/images/member/riku.jpeg',
        birth: new Date('2002-10-26'),
        type: 'AB',
        artistId: 4,
      },
      {
        eName: 'Ayaka',
        jName: 'アヤカ',
        photo: '/images/member/ayaka.jpeg',
        birth: new Date('2003-06-20'),
        type: 'A',
        artistId: 4,
      },
      {
        eName: 'Mayuka',
        jName: 'マユカ',
        photo: '/images/member/mayuka.jpeg',
        birth: new Date('2003-11-13'),
        type: 'A',
        artistId: 4,
      },
      {
        eName: 'Rima',
        jName: 'リマ',
        photo: '/images/member/rima.jpeg',
        birth: new Date('2004-03-26'),
        type: 'O',
        artistId: 4,
      },
      {
        eName: 'Miihi',
        jName: 'ミイヒ',
        photo: '/images/member/miihi.jpeg',
        birth: new Date('204-08-12'),
        type: 'O',
        artistId: 4,
      },
      {
        eName: 'Nina',
        jName: 'ニナ',
        photo: '/images/member/nina.jpeg',
        birth: new Date('2005-02-27'),
        type: 'O',
        artistId: 4,
      },
      // NMIXX
      {
        eName: 'Lily',
        jName: 'リリー',
        photo: '/images/member/lily.jpeg',
        birth: new Date('2002-10-17'),
        type: 'O',
        artistId: 5,
      },
      {
        eName: 'Haewon',
        jName: 'へウォン',
        photo: '/images/member/haewon.jpeg',
        birth: new Date('2003-02-25'),
        type: 'O',
        artistId: 5,
      },
      {
        eName: 'Sullyoon',
        jName: 'ソリュン',
        photo: '/images/member/sullyoon.jpeg',
        birth: new Date('2004-01-26'),
        type: 'A',
        artistId: 5,
      },
      {
        eName: 'Bae',
        jName: 'ベイ',
        photo: '/images/member/bae.jpeg',
        birth: new Date('2004-12-28'),
        type: 'B',
        artistId: 5,
      },
      {
        eName: 'Jiwoo',
        jName: 'ジウ',
        photo: '/images/member/jiwoo.jpeg',
        birth: new Date('2005-04-13'),
        type: 'AB',
        artistId: 5,
      },
      {
        eName: 'Kyujin',
        jName: 'ギュジン',
        photo: '/images/member/kyujin.jpeg',
        birth: new Date('2006-05-26'),
        type: 'A',
        artistId: 5,
      },
      // Girls'Generation
      {
        eName: 'YoonA',
        jName: 'ユナ',
        photo: '/images/member/yoona.jpeg',
        birth: new Date('1990-05-30'),
        type: 'B',
        artistId: 6,
      },
      {
        eName: 'SooYoung',
        jName: 'スヨン',
        photo: '/images/member/sooyoung.jpeg',
        birth: new Date('1990-02-10'),
        type: 'O',
        artistId: 6,
      },
      {
        eName: 'YuRi',
        jName: 'ユリ',
        photo: '/images/member/yuri.jpeg',
        birth: new Date('1989-12-05'),
        type: 'AB',
        artistId: 6,
      },
      {
        eName: 'SeoHyun',
        jName: 'ソヒョン',
        photo: '/images/member/seohyun.jpeg',
        birth: new Date('1991-06-28'),
        type: 'A',
        artistId: 6,
      },
      {
        eName: 'TaeYeon',
        jName: 'テヨン',
        photo: '/images/member/taeyeon.jpeg',
        birth: new Date('1989-03-09'),
        type: 'A',
        artistId: 6,
      },
      {
        eName: 'Sunny',
        jName: 'サニー',
        photo: '/images/member/sunny.jpeg',
        birth: new Date('1989-05-15'),
        type: 'B',
        artistId: 6,
      },
      {
        eName: 'HyoYeon',
        jName: 'ヒョヨン',
        photo: '/images/member/yoona.jpeg',
        birth: new Date('1989-09-22'),
        type: 'AB',
        artistId: 6,
      },
      {
        eName: 'Tiffany',
        jName: 'ティファニー',
        photo: '/images/member/tiffany.jpeg',
        birth: new Date('1989-08-01'),
        type: 'O',
        artistId: 6,
      },
      // RedVelvet
      {
        eName: 'Irene',
        jName: 'アイリーン',
        photo: '/images/member/irene.webg',
        birth: new Date('1991-03-29'),
        type: 'A',
        artistId: 7,
      },
      {
        eName: 'Seulgi',
        jName: 'スルギ',
        photo: '/images/member/seulgi.webg',
        birth: new Date('1994-02-10'),
        type: 'A',
        artistId: 7,
      },
      {
        eName: 'Wendy',
        jName: 'ウェンディ',
        photo: '/images/member/wendy.webg',
        birth: new Date('1994-02-21'),
        type: 'O',
        artistId: 7,
      },
      {
        eName: 'Joy',
        jName: 'ジョイ',
        photo: '/images/member/joy.webg',
        birth: new Date('1996-09-03'),
        type: 'A',
        artistId: 7,
      },
      {
        eName: 'Yeri',
        jName: 'イェリ',
        photo: '/images/member/yeri.webg',
        birth: new Date('1999-03-05'),
        type: 'O',
        artistId: 7,
      },
      // aespa
      {
        eName: 'Karina',
        jName: 'カリナ',
        photo: '/images/member/karina.jpg',
        birth: new Date('2000-04-11'),
        type: 'B',
        artistId: 8,
      },
      {
        eName: 'Winter',
        jName: 'ウィンター',
        photo: '/images/member/winter.jpg',
        birth: new Date('2001-01-01'),
        type: 'A',
        artistId: 8,
      },
      {
        eName: 'NingNing',
        jName: 'ニンニン',
        photo: '/images/member/ningning.jpg',
        birth: new Date('2002-10-23'),
        type: 'B',
        artistId: 8,
      },
      {
        eName: 'Giselle',
        jName: 'ジゼル',
        photo: '/images/member/giselle.jpg',
        birth: new Date('2000-10-30'),
        type: 'O',
        artistId: 8,
      },
      // BigBang
      {
        eName: 'G-DRAGON',
        jName: 'ジードラゴン',
        photo: '/images/member/g-doragon.webp',
        birth: new Date('1988-08-18'),
        type: 'A',
        artistId: 9,
      },
      {
        eName: 'T.O.P',
        jName: 'トップ',
        photo: '/images/member/t.o.p.webp',
        birth: new Date('1987-11-04'),
        type: 'B',
        artistId: 9,
      },
      {
        eName: 'SOL',
        jName: 'ソル',
        photo: '/images/member/sol.webp',
        birth: new Date('1988-05-18'),
        type: 'B',
        artistId: 9,
      },
      {
        eName: 'D-LITE',
        jName: 'ディライト',
        photo: '/images/member/d-lite.webp',
        birth: new Date('1989-04-26'),
        type: 'O',
        artistId: 9,
      },
      // Black Pink
      {
        eName: 'JENNIE',
        jName: 'ジェニー',
        photo: '/images/member/jennie.webp',
        birth: new Date('1996-01-16'),
        type: 'B',
        artistId: 10,
      },
      {
        eName: 'LISA',
        jName: 'リサ',
        photo: '/images/member/lisa.webp',
        birth: new Date('1997-03-27'),
        type: '',
        artistId: 10,
      },
      {
        eName: 'JISOO',
        jName: 'ジス',
        photo: '/images/member/jisoo.webp',
        birth: new Date('1995-01-03'),
        type: 'A',
        artistId: 10,
      },
      {
        eName: 'ROSÉ',
        jName: 'ロゼ',
        photo: '/images/member/rose.webp',
        birth: new Date('1997-02-11'),
        type: 'B',
        artistId: 10,
      },
      // BTS
      {
        eName: 'RM',
        jName: 'アールエム',
        photo: '/images/member/rm.jpeg',
        birth: new Date('1994-09-12'),
        type: 'A',
        artistId: 11,
      },
      {
        eName: 'SUGA',
        jName: 'シュガ',
        photo: '/images/member/suga.jpeg',
        birth: new Date('1993-03-09'),
        type: 'O',
        artistId: 11,
      },
      {
        eName: 'JIN',
        jName: 'ジン',
        photo: '/images/member/jin.jpeg',
        birth: new Date('1992-12-04'),
        type: 'O',
        artistId: 11,
      },
      {
        eName: 'J-HOPE',
        jName: 'ジェイホープ',
        photo: '/images/member/j-hope.jpeg',
        birth: new Date('1994-02-18'),
        type: 'A',
        artistId: 11,
      },
      {
        eName: 'JIMIN',
        jName: 'ジミン',
        photo: '/images/member/jimin.jpeg',
        birth: new Date('199-10-13'),
        type: 'A',
        artistId: 11,
      },
      {
        eName: 'V',
        jName: 'ヴィ',
        photo: '/images/member/v.jpeg',
        birth: new Date('1995-12-30'),
        type: 'AB',
        artistId: 11,
      },
      {
        eName: 'JUNG KOOK',
        jName: 'ジョングク',
        photo: '/images/member/jungkook.jpeg',
        birth: new Date('1997-09-01'),
        type: 'A',
        artistId: 11,
      },
      // fromis_9
      {
        eName: 'BAEK JIHEON',
        jName: 'ペク・ジホン',
        photo: '/images/member/baek-jiheon.jpeg',
        birth: new Date('2003-04-17'),
        type: 'B',
        artistId: 12,
      },
      {
        eName: 'LEE NAGYUNG',
        jName: 'イ・ナギョン',
        photo: '/images/member/lee-nagyung.jpeg',
        birth: new Date('2000-06-01'),
        type: 'A',
        artistId: 12,
      },
      {
        eName: 'LEE CHAEYOUNG',
        jName: 'イ・チェヨン',
        photo: '/images/member/lee-chaeyoung.jpeg',
        birth: new Date('2000-05-14'),
        type: 'B',
        artistId: 12,
      },
      {
        eName: 'LEE SEOYEON',
        jName: 'イ・ソヨン',
        photo: '/images/member/lee-seoyeon.jpeg',
        birth: new Date('2000-01-22'),
        type: 'A',
        artistId: 12,
      },
      {
        eName: 'ROH JISUN',
        jName: 'ノ・ジソン',
        photo: '/images/member/roh-jisun.jpeg',
        birth: new Date('1998-11-23'),
        type: 'B',
        artistId: 12,
      },
      {
        eName: 'PARK JIWON',
        jName: 'パク・ジウォン',
        photo: '/images/member/park-jiwon.jpeg',
        birth: new Date('1998-03-20'),
        type: 'A',
        artistId: 12,
      },
      {
        eName: 'SONG HAYOUNG',
        jName: 'ソン・ハヨン',
        photo: '/images/member/song-hayoung.jpeg',
        birth: new Date('1997-09-29'),
        type: 'A',
        artistId: 12,
      },
      {
        eName: 'LEE SAEROM',
        jName: 'イ・セロム',
        photo: '/images/member/lee-saerom.png',
        birth: new Date('1997-01-07'),
        type: 'B',
        artistId: 12,
      },
      // LE SSERAFIM
      {
        eName: 'KIM CHAEWON',
        jName: 'キム・チェウォン',
        photo: '/images/member/kim-chaewon.jpeg',
        birth: new Date('2000-08-01'),
        type: 'B',
        artistId: 13,
      },
      {
        eName: 'SAKURA',
        jName: 'サクラ',
        photo: '/images/member/sakura.jpeg',
        birth: new Date('1998-03-19'),
        type: 'A',
        artistId: 13,
      },
      {
        eName: 'HUH YUNJIN',
        jName: 'ホ・ユンジン',
        photo: '/images/member/huh-yunjin.jpeg',
        birth: new Date('2001-10-08'),
        type: 'B',
        artistId: 13,
      },
      {
        eName: 'KAZUHA',
        jName: 'カズハ',
        photo: '/images/member/kazuha.jpeg',
        birth: new Date('2003-08-09'),
        type: '-',
        artistId: 13,
      },
      {
        eName: 'HONG EUNCHAE',
        jName: 'ホン・ウンチェ',
        photo: '/images/member/hong-eunchae.jpeg',
        birth: new Date('2006-11-10'),
        type: '-',
        artistId: 13,
      },
      // NEWJEANS
      {
        eName: 'MINJI',
        jName: 'ミンジ',
        photo: '/images/member/minji.jpeg',
        birth: new Date('2004-05-07'),
        type: '-',
        artistId: 14,
      },
      {
        eName: 'HANNI',
        jName: 'ハニ',
        photo: '/images/member/hanni.jpeg',
        birth: new Date('2004-10-06'),
        type: '-',
        artistId: 14,
      },
      {
        eName: 'DANIELLE',
        jName: 'ダニエル',
        photo: '/images/member/danielle.jpeg',
        birth: new Date('2005-04-11'),
        type: 'AB',
        artistId: 14,
      },
      {
        eName: 'HAERIN',
        jName: 'ヘリン',
        photo: '/images/member/haerin.jpeg',
        birth: new Date('2006-05-15'),
        type: '-',
        artistId: 14,
      },
      {
        eName: 'HYEIN',
        jName: 'ヘイン',
        photo: '/images/member/hyein.jpeg',
        birth: new Date('2008-04-21'),
        type: '-',
        artistId: 14,
      },
      // Billlie
      {
        eName: 'TSUKI',
        jName: 'ツキ',
        photo: '/images/member/tsuki.jpeg',
        birth: new Date('2002-09-21'),
        type: 'O',
        artistId: 15,
      },
      {
        eName: 'MOON SUA',
        jName: 'ムン・スア',
        photo: '/images/member/moon-sua.jpeg',
        birth: new Date('1999-09-09'),
        type: 'O',
        artistId: 15,
      },
      {
        eName: 'HARAM',
        jName: 'ハラム',
        photo: '/images/member/haram.jpeg',
        birth: new Date('2001-01-13'),
        type: 'O',
        artistId: 15,
      },
      {
        eName: 'SUHYEON',
        jName: 'スヒョン',
        photo: '/images/member/suhyeon.jpeg',
        birth: new Date('2000-01-15'),
        type: 'O',
        artistId: 15,
      },
      {
        eName: 'HARUNA',
        jName: 'ハルナ',
        photo: '/images/member/haruna.jpeg',
        birth: new Date('2006-01-30'),
        type: '-',
        artistId: 15,
      },
      {
        eName: 'SIYOON',
        jName: 'シユン',
        photo: '/images/member/siyoon.jpeg',
        birth: new Date('2005-02-16'),
        type: '-',
        artistId: 15,
      },
      {
        eName: 'SHEON',
        jName: 'ション',
        photo: '/images/member/sheon.jpeg',
        birth: new Date('2003-01-28'),
        type: 'A',
        artistId: 15,
      },
      // NATURE
      {
        eName: 'CHAEBIN',
        jName: 'チェビン',
        photo: '/images/member/chaebin.jpeg',
        birth: new Date('1999-07-28'),
        type: 'B',
        artistId: 16,
      },
      {
        eName: 'SUNSHINE',
        jName: 'サンシャイン',
        photo: '/images/member/sunshine.jpeg',
        birth: new Date('2002-06-20'),
        type: 'O',
        artistId: 16,
      },
      {
        eName: 'UCHAE',
        jName: 'ユチェ',
        photo: '/images/member/uchae.jpeg',
        birth: new Date('2002-05-07'),
        type: 'A',
        artistId: 16,
      },
      {
        eName: 'SAEBOM',
        jName: 'セボム',
        photo: '/images/member/saebom.jpeg',
        birth: new Date('1997-01-30'),
        type: 'AB',
        artistId: 16,
      },
      {
        eName: 'LU',
        jName: 'ルー',
        photo: '/images/member/lu.jpeg',
        birth: new Date('1997-12-03'),
        type: 'O',
        artistId: 16,
      },
      {
        eName: 'LOHA',
        jName: 'ロハ',
        photo: '/images/member/roha.jpeg',
        birth: new Date('2001-12-27'),
        type: 'A',
        artistId: 16,
      },
      {
        eName: 'AURORA',
        jName: 'オーロラ',
        photo: '/images/member/aurora.jpeg',
        birth: new Date('1997-01-14'),
        type: 'B',
        artistId: 16,
      },
      {
        eName: 'HARU',
        jName: 'ハル',
        photo: '/images/member/haru.jpeg',
        birth: new Date('2000-02-21'),
        type: 'B',
        artistId: 16,
      },
      {
        eName: 'SOHEE',
        jName: 'ソヒ',
        photo: '/images/member/sohee.jpeg',
        birth: new Date('1995-01-20'),
        type: 'A',
        artistId: 16,
      },
      // MAMAMOO
      {
        eName: 'Solar',
        jName: 'ソラ',
        photo: '/images/member/solar.jpeg',
        birth: new Date('1991-02-21'),
        type: 'B',
        artistId: 17,
      },
      {
        eName: 'Moon Byul',
        jName: 'ムンビョル',
        photo: '/images/member/moonbyul.jpeg',
        birth: new Date('1992-12-22'),
        type: 'B',
        artistId: 17,
      },
      {
        eName: 'Whee In',
        jName: 'フィイン',
        photo: '/images/member/wheein.jpeg',
        birth: new Date('1995-04-17'),
        type: 'B',
        artistId: 17,
      },
      {
        eName: 'Hwa Sa',
        jName: 'ファサ',
        photo: '/images/member/hwasa.jpeg',
        birth: new Date('1995-07-23'),
        type: 'A',
        artistId: 17,
      },
      // Kep1er
      {
        eName: 'YUJIN',
        jName: 'ユジン',
        photo: '/images/member/yujin.jpeg',
        birth: new Date('1996-08-12'),
        type: 'A',
        artistId: 18,
      },
      {
        eName: 'XIAOTING',
        jName: 'シャオティン',
        photo: '/images/member/xiaoting.jpeg',
        birth: new Date('1999-11-12'),
        type: 'AB',
        artistId: 18,
      },
      {
        eName: 'MASHIRO',
        jName: 'マシロ',
        photo: '/images/member/mashiro.jpeg',
        birth: new Date('1999-12-16'),
        type: 'AB',
        artistId: 18,
      },
      {
        eName: 'CHAEHYUN',
        jName: 'チェヒョン',
        photo: '/images/member/chaehyun.jpeg',
        birth: new Date('2002-04-26'),
        type: 'B',
        artistId: 18,
      },
      {
        eName: 'DAYEON',
        jName: 'ダヨン',
        photo: '/images/member/dayeon.jpeg',
        birth: new Date('2003-03-02'),
        type: 'A',
        artistId: 18,
      },
      {
        eName: 'HIKARU',
        jName: 'ヒカル',
        photo: '/images/member/hikaru.jpeg',
        birth: new Date('2004-03-12'),
        type: 'O',
        artistId: 18,
      },
      {
        eName: 'HUENING BAHIYYIH',
        jName: 'ヒュニン バヒエ',
        photo: '/images/member/huening-bahiyyih.jpeg',
        birth: new Date('2004-07-27'),
        type: 'A',
        artistId: 18,
      },
      {
        eName: 'YOUNGEUN',
        jName: 'ヨンウン',
        photo: '/images/member/youngeun.jpeg',
        birth: new Date('2004-12-27'),
        type: 'A',
        artistId: 18,
      },
      {
        eName: 'YESEO',
        jName: 'イェソ',
        photo: '/images/member/yeseo.jpeg',
        birth: new Date('2005-08-22'),
        type: 'A',
        artistId: 18,
      },
      // (G)I-DLE
      {
        eName: 'MIYEON',
        jName: 'ミヨン',
        photo: '/images/member/miyeon.jpeg',
        birth: new Date('1997-01-31'),
        type: 'B',
        artistId: 19,
      },
      {
        eName: 'MINNIE',
        jName: 'ミンニ',
        photo: '/images/member/minnie.jpeg',
        birth: new Date('1997-10-23'),
        type: 'O',
        artistId: 19,
      },
      {
        eName: 'SOYEON',
        jName: 'ソヨン',
        photo: '/images/member/soyeon.jpeg',
        birth: new Date('1998-08-26'),
        type: 'B',
        artistId: 19,
      },
      {
        eName: 'YUQI',
        jName: 'ウギ',
        photo: '/images/member/yuqi.jpeg',
        birth: new Date('1999-09-23'),
        type: 'O',
        artistId: 19,
      },
      {
        eName: 'SHUHUA',
        jName: 'シュファ',
        photo: '/images/member/shuhu.jpeg',
        birth: new Date('2000-01-06'),
        type: 'A',
        artistId: 19,
      },
      // MOMOLAND
      {
        eName: 'NANCY',
        jName: 'ナンシー',
        photo: '/images/member/nancy.jpeg',
        birth: new Date('2000-04-13'),
        type: 'O',
        artistId: 20,
      },
      {
        eName: 'JOO E',
        jName: 'ジュイ',
        photo: '/images/member/joo-e.jpeg',
        birth: new Date('1999-08-18'),
        type: 'O',
        artistId: 20,
      },
      {
        eName: 'AH IN',
        jName: 'アイン',
        photo: '/images/member/ah-in.jpeg',
        birth: new Date('1999-09-27'),
        type: 'A',
        artistId: 20,
      },
      {
        eName: 'HYE BIN',
        jName: 'ヘビン',
        photo: '/images/member/hye-bin.jpeg',
        birth: new Date('1996-01-12'),
        type: 'B',
        artistId: 20,
      },
      {
        eName: 'NA YUN',
        jName: 'ナユン',
        photo: '/images/member/na-yun.jpeg',
        birth: new Date('1998-07-31'),
        type: 'AB',
        artistId: 20,
      },
      {
        eName: 'JANE',
        jName: 'ジェイン',
        photo: '/images/member/jane.jpeg',
        birth: new Date('1997-12-20'),
        type: 'O',
        artistId: 20,
      },
    ],
  });
}

async function feedData() {
  await feedOffice();
  await feedArtist();
  await feedMusic();
  await feedMember();
}

const main = async () => {
  await feedData();
};

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
